-- AlterEnum
-- Migration generated for change `text-command-bot` (WU1).
-- Replaces the ConversationState enum: removes ESPERANDO_IMAGEN, VALIDANDO_DATOS;
-- adds PREGUNTANDO_PRODUCTO, PREGUNTANDO_COSTO_LOTE, AGREGANDO_STOCK.
-- Also drops the imagenOriginal column from Compra (no longer needed without OCR).
--
-- NOTE: This is a dev-only migration. If any rows still use the removed enum values,
-- the USING cast will fail. In dev that's acceptable — just truncate Conversacion first.
--
-- Generated by `prisma migrate diff` pattern (no dev DB available locally),
-- comparing pre-WU1 schema to post-WU1 schema.

-- 1. Create new enum type with the updated values
CREATE TYPE "ConversationState_new" AS ENUM (
  'PREGUNTANDO_PRODUCTO',
  'PREGUNTANDO_CANTIDAD',
  'PREGUNTANDO_UNIDAD',
  'PREGUNTANDO_COSTO_LOTE',
  'PREGUNTANDO_PRECIO_VENTA',
  'CONFIRMACION_FINAL',
  'GUARDADO',
  'AGREGANDO_STOCK'
);

-- 2. Migrate the column (drop default first, cast, then set new default)
ALTER TABLE "Conversacion" ALTER COLUMN "estado" DROP DEFAULT;
ALTER TABLE "Conversacion"
  ALTER COLUMN "estado" TYPE "ConversationState_new"
  USING "estado"::text::"ConversationState_new";
ALTER TABLE "Conversacion" ALTER COLUMN "estado" SET DEFAULT 'PREGUNTANDO_PRODUCTO';

-- 3. Drop old enum type and rename new one
DROP TYPE "ConversationState";
ALTER TYPE "ConversationState_new" RENAME TO "ConversationState";

-- 4. Remove imagenOriginal column from Compra
ALTER TABLE "Compra" DROP COLUMN "imagenOriginal";
