-- AlterEnum
-- Migration generated for change `ocr-parser-label-aware` (WU1).
-- Adds the new `LOTE` value to the existing PostgreSQL enum `Unidad`.
-- This is an additive, non-breaking change: existing rows with the
-- previous 5 values (UNIDAD/PAR/PACK/CAJA/OTRO) are unaffected.
--
-- Generated by `prisma migrate diff` (no dev DB available locally),
-- comparing the pre-WU1 schema (git ref: main) to the post-WU1 schema.

ALTER TYPE "Unidad" ADD VALUE 'LOTE';
